services:
  openvpn:
    image: ubuntu-openvpn
    build: .
    container_name: ubuntu-openvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "${VPN_PORT}:1194/udp"
    volumes:
      - ubuntu-openvpn-data:/etc/openvpn/ca
      - ./sh:/etc/openvpn/sh/
      - ./clients:/etc/openvpn/clients/
      - ./server.conf:/etc/openvpn/server.conf
    environment:
      - TZ=Asia/Tokyo
      - VPN_GLOBAL_IP=${VPN_GLOBAL_IP}
      - VPN_PORT=${VPN_PORT}
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "test", "-f", "/etc/openvpn/ca/easyrsa/pki/ca.crt" ]
      interval: 30s
      timeout: 5s
      retries: 2
      start_period: 20s

volumes:
  ubuntu-openvpn-data:
